SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: audit_log_entries; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: flow_state; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: users; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: identities; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: instances; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: sessions; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: mfa_amr_claims; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: mfa_factors; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: mfa_challenges; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: one_time_tokens; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: sso_providers; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: saml_providers; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: saml_relay_states; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: sso_domains; Type: TABLE DATA; Schema: auth; Owner: supabase_auth_admin
--



--
-- Data for Name: key; Type: TABLE DATA; Schema: pgsodium; Owner: supabase_admin
--



--
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "public"."companies" ("id", "name", "slug", "website", "logo_url", "description", "founded_year", "headquarters", "employee_count", "revenue_usd", "public_company", "stock_symbol", "stock_exchange", "created_at", "updated_at") VALUES
	(6, 'Verona Pharma plc', 'verona-pharma-plc', 'https://www.veronapharma.com', 'https://images.financialmodelingprep.com/symbol/VRNA.png', 'Verona Pharma plc, a clinical stage biopharmaceutical company, focuses on development and commercialization of therapies for the treatment of respiratory diseases with unmet medical needs. The company''s product candidate is ensifentrine, an inhaled and dual inhibitor of the phosphodiesterase (PDE) 3 and PDE4 enzymes that acts as both a bronchodilator and an anti-inflammatory agent in a single compound, which is in Phase 3 clinical trials for the treatment of chronic obstructive pulmonary disease, asthma, and cystic fibrosis. It is developing ensifentrine in three formulations, including nebulizer, dry powder inhaler, and pressurized metered-dose inhaler. Verona Pharma plc was incorporated in 2005 and is headquartered in London, the United Kingdom.', 2017, 'London, GB', 209, NULL, true, 'VRNA', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(7, 'BioNTech SE', 'biontech-se', 'https://www.biontech.de', 'https://images.financialmodelingprep.com/symbol/BNTX.png', 'BioNTech SE, a biotechnology company, develops and commercializes immunotherapies for cancer and other infectious diseases. The company is developing FixVac product candidates, including BNT111, which is in Phase II clinical trial for advance melanoma; BNT112 that is in Phase I/IIa clinical trial for prostate cancer; BNT113, which is in Phase II clinical trial to treat HPV+ head and neck cancers; BNT114 that is in Phase I clinical trial for triple negative breast cancer; BNT115, which is in Phase I clinical trial in ovarian cancer; and BNT116, a preclinical stage product for non-small cell lung cancer. It also develops neoantigen specific immunotherapies, such as Autogene cevumeran (BNT122), which is in Phase II clinical trial for first-line melanoma, as well as in Phase 1a/1b clinical trial to treat multiple solid tumors; mRNA intratumoral immunotherapy comprising SAR441000 that is in Phase I clinical trial for solid tumors; and BNT141 and BNT142 that are in Phase I clinical trial to treat multiple solid tumors. In addition, the company develops RiboCytokines, which include BNT151, BNT152, and BNT153 to treat solid tumors; chimeric antigen receptor T cell immunotherapies, such as BNT211 to treat multiple solid tumors, and BNT221 for other cancers; and checkpoint immunomodulators consisting of GEN1046 and GEN1042, which are in Phase I/II clinical trial to treat solid tumors. Further, it develops BNT321, an IgG1 monoclonal antibody in Phase II clinical trial for pancreatic cancer; BNT411, a small molecule immunomodulator product candidate for solid tumors; prophylactic vaccine for COVID-19 and Influenza; and infectious disease immunotherapies and rare disease protein replacement therapies. The company has collaborations with Genentech, Inc.; Sanofi S.A.; Genmab A/S; Pfizer Inc.; Shanghai Fosun Pharmaceutical (Group) Co., Ltd.; and Regeneron Pharmaceuticals, Inc. BioNTech SE was incorporated in 2008 and is headquartered in Mainz, Germany.', 2019, 'Mainz, DE', 6133, NULL, true, 'BNTX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(8, 'Mesoblast Limited', 'mesoblast-limited', 'https://www.mesoblast.com', 'https://images.financialmodelingprep.com/symbol/MESO.png', 'Mesoblast Limited, a biopharmaceutical company, develops and commercializes allogeneic cellular medicines in the United States, Australia, Singapore, the United Kingdom, and Switzerland. The company offers products in the areas of cardiovascular, spine orthopedic disorder, oncology, hematology, and immune-mediated and inflammatory diseases. Its proprietary regenerative medicine technology platform is based on specialized cells known as mesenchymal lineage cells. The company''s products under the Phase III clinical trials include remestemcel-L for the treatment of steroid refractory acute graft versus host disease, as well as acute respiratory distress syndrome due to COVID-19 infection; Rexlemestrocel-L to treat advanced chronic heart failure; and MPC-06-ID for chronic low back pain due to degenerative disc disease. It is also developing MPC-300-IV for the treatment of biologic refractory rheumatoid arthritis diabetic nephropathy. The company has strategic partnerships with Tasly Pharmaceutical Group to offer MPC-150-IM for heart failure and MPC-25-IC for heart attacks in China; JCR Pharmaceuticals Co. Ltd. for the treatment of wound healing in patients with epidermolysis bullosa; and Grünenthal to develops and commercializes cell therapy for the treatment of chronic low back pain. Mesoblast Limited was incorporated in 2004 and is headquartered in Melbourne, Australia.', 2010, 'Melbourne, VIC, AU', 73, NULL, true, 'MESO', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(9, 'Royalty Pharma plc', 'royalty-pharma-plc', 'https://www.royaltypharma.com', 'https://images.financialmodelingprep.com/symbol/RPRX.png', 'Royalty Pharma plc operates as a buyer of biopharmaceutical royalties and a funder of innovations in the biopharmaceutical industry in the United States. It is also involved in the identification, evaluation, and acquisition of royalties on various biopharmaceutical therapies. In addition, the company collaborates with innovators from academic institutions, research hospitals and not-for-profits, small and mid-cap biotechnology companies, and pharmaceutical companies. Its portfolio consists of royalties on approximately 35 marketed therapies and 10 development-stage product candidates that address various therapeutic areas, such as rare disease, cancer, neurology, infectious disease, hematology, and diabetes. The company was founded in 1996 and is based in New York, New York.', 2020, 'New York, NY, US', 75, NULL, true, 'RPRX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(10, 'Alnylam Pharmaceuticals, Inc.', 'alnylam-pharmaceuticals-inc', 'https://www.alnylam.com', 'https://images.financialmodelingprep.com/symbol/ALNY.png', 'Alnylam Pharmaceuticals, Inc., a biopharmaceutical company, focuses on discovering, developing, and commercializing novel therapeutics based on ribonucleic acid interference. The company''s pipeline of investigational RNAi therapeutics focuses on genetic medicines, cardio-metabolic diseases, hepatic infectious diseases, and central nervous system (CNS)/ocular diseases. Its marketed products include ONPATTRO (patisiran), a lipid complex injection for the treatment of the polyneuropathy of hereditary transthyretin-mediated amyloidosis in adults; GIVLAARI for the treatment of adults with acute hepatic porphyria (AHP); and OXLUMO (lumasiran) for the treatment of primary hyperoxaluria type 1 (PH1). In addition, the company is developing givosiran for the treatment of adolescent patients with AHP; patisiran for the treatment of transthyretin amyloidosis, or ATTR amyloidosis, with cardiomyopathy; cemdisiran to treat complement-mediated diseases; ALN-AAT02 for the treatment of AAT deficiency-associated liver disease; ALN-HBV02 to treat chronic HBV infection; Zilebesiran to treat hypertension; and ALN-HSD to treat NASH. Further, it offers Fitusiran for the treatment of hemophilia and rare bleeding disorders, Inclisiran to treat hypercholesterolemia, lumasiran for the treatment of advanced PH1 and recurrent renal stones, and vutrisiran for the treatment of ATTR amyloidosis, which is in phase 3 clinical trial. Alnylam Pharmaceuticals, Inc. has strategic collaborations with Regeneron Pharmaceuticals, Inc. to discover, develop, and commercialize RNAi therapeutics for a range of diseases by addressing therapeutic targets expressed in the eye and CNS; and Sanofi Genzyme to discover, develop, and commercialize RNAi therapeutics. It also has license and collaboration agreements with Novartis AG; Vir Biotechnology, Inc.; Dicerna Pharmaceuticals, Inc.; Ionis Pharmaceuticals, Inc.; and PeptiDream, Inc. The company was founded in 2002 and is headquartered in Cambridge, Massachusetts.', 2004, 'Cambridge, MA, US', 2230, NULL, true, 'ALNY', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(11, 'argenx SE', 'argenx-se', 'https://www.argenx.com', 'https://images.financialmodelingprep.com/symbol/ARGX.png', 'argenx SE, a biotechnology company, engages in the developing of various therapies for the treatment of autoimmune diseases in the United States, Japan, Europe, Middle East, Africa, and China. Its lead product candidate is efgartigimod for the treatment of patients with myasthenia gravis, immune thrombocytopenia, pemphigus vulgaris, generalized myasthenia gravis, chronic inflammatory demyelinating polyneuropathy, thyroid eye disease, bullous pemphigoid, myositis, primary sjögren''s syndrome, post-covid postural orthostatic tachycardia syndrome, membranous nephropathy, lupus nephropathy, anca-associated vasculitis, and antibody mediated rejection; ENHANZE SC; Empasiprubart for multifocal motor neuropath, delayed graft function, and dermatomyositis; and ARGX-119 for congenital myasthenic syndrome and amyotrophic lateral sclerosis. The company is developing ARGX-213 targets FcRn; ARGX-121 and ARGX-220 targets immune system; ARGX-109 targets IL-6; ARGX-118 for inflammation; and ARGX-109, as well as cusatuzumab, ARGX-112, ARGX-114, and ARGX-115. It owns VYVGART; VYVGART HYTRULO; VYVDURA; ARGENX; ABDEG; NHANCE; SIMPLE ANTIBODY; and ARGENXMEDHUB. The company has strategic partnership with AbbVie S.À.R.L., Zai Lab Limited, and LEO Pharma A/S; and collaboration and license agreement with Genor Biopharma Co. Ltd, Université Catholique de Louvain, Sopartec S.A., NYU Langone Health, Leiden University Medical Center, AgomAb Therapeutics NV, Broteio Pharma B.V., VIB vzw, University of Texas, BioWa, Inc., and Shire International GmbH. It has collaboration agreement with Genmab A/S to discover, develop, and commercialize novel therapeutic antibodies with applications in immunology and oncology, as well as a strategic collaboration with IQVIA Holdings Inc. to provide safety systems and services. argenx SE was incorporated in 2008 and is based in Amsterdam, the Netherlands.', 2017, 'Amsterdam, NL', 1148, NULL, true, 'ARGX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(12, 'Alterity Therapeutics Limited', 'alterity-therapeutics-limited', 'https://alteritytherapeutics.com', 'https://images.financialmodelingprep.com/symbol/ATHE.png', 'Alterity Therapeutics Limited engages in the research and development of therapeutic drugs to treat Alzheimer''s disease, Huntington disease, Parkinson''s disease, and other neurological disorders in Australia. The company''s lead drug candidate is ATH434 that has completed Phase I clinical trial for the treatment of Parkinson''s disease. It is also developing PBT2 that has completed Phase IIa clinical trial to treat Alzheimer''s disease. The company was formerly known as Prana Biotechnology Limited and changed its name to Alterity Therapeutics Limited in April 2019. Alterity Therapeutics Limited was incorporated in 1997 and is headquartered in Melbourne, Australia.', 2003, 'Melbourne, VIC, AU', 10, NULL, true, 'ATHE', 'NASDAQ Capital Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(13, 'Regeneron Pharmaceuticals, Inc.', 'regeneron-pharmaceuticals-inc', 'https://www.regeneron.com', 'https://images.financialmodelingprep.com/symbol/REGN.png', 'Regeneron Pharmaceuticals, Inc. discovers, invents, develops, manufactures, and commercializes medicines for treating various diseases worldwide. The company''s products include EYLEA injection to treat wet age-related macular degeneration and diabetic macular edema; myopic choroidal neovascularization; and diabetic retinopathy, as well as macular edema following retinal vein occlusion, including macular edema following central retinal vein occlusion and macular edema following branch retinal vein occlusion. It also provides Dupixent injection to treat atopic dermatitis and asthma in adults and pediatrics; Libtayo injection to treat metastatic or locally advanced cutaneous squamous cell carcinoma;Praluent injection for heterozygous familial hypercholesterolemia or clinical atherosclerotic cardiovascular disease in adults; REGEN-COV for covid-19; and Kevzara solution for treating rheumatoid arthritis in adults. In addition, the company offers Inmazeb injection for infection caused by Zaire ebolavirus; ARCALYST injection for cryopyrin-associated periodic syndromes, including familial cold auto-inflammatory syndrome and muckle-wells syndrome; and ZALTRAP injection for intravenous infusion to treat metastatic colorectal cancer; and develops product candidates for treating patients with eye, allergic and inflammatory, cardiovascular and metabolic, infectious, and rare diseases; and cancer, pain, and hematologic conditions. It has collaboration and license agreements with Sanofi; Bayer; Teva Pharmaceutical Industries Ltd.; Mitsubishi Tanabe Pharma Corporation; Alnylam Pharmaceuticals, Inc.; Roche Pharmaceuticals; and Kiniksa Pharmaceuticals, Ltd., as well as has an agreement with the U.S. Department of Health and Human Services, as well as with Zai Lab Limited; Intellia Therapeutics, Inc.; Biomedical Advanced Research Development Authority; and AstraZeneca PLC. The company was incorporated in 1988 and is headquartered in Tarrytown, New York.', 1991, 'Tarrytown, NY, US', 15106, NULL, true, 'REGN', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(14, 'Summit Therapeutics Inc.', 'summit-therapeutics-inc', 'https://www.summittxinc.com', 'https://images.financialmodelingprep.com/symbol/SMMT.png', 'Summit Therapeutics Inc., a biopharmaceutical company, discovers, develops, and commercializes medicines to treat infectious diseases in the United States and Latin America. It conducts clinical programs focusing on Clostridioides difficile infection (CDI). The company''s lead product candidate is ridinilazole, an orally administered small molecule antibiotic that is in Phase III clinical trials for the treatment of CDI. It also offers SMT-738, for combating multidrug resistant infections primarily carbapenem-resistant Enterobacteriaceae infections; and DDS-04 series for the potential treatment of infections caused by the Enterobacteriaceae. The company was founded in 2003 and is based in Cambridge, Massachusetts.', 2015, 'Cambridge, MA, US', 159, NULL, true, 'SMMT', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(15, 'Vertex Pharmaceuticals Incorporated', 'vertex-pharmaceuticals-incorporated', 'https://www.vrtx.com', 'https://images.financialmodelingprep.com/symbol/VRTX.png', 'Vertex Pharmaceuticals Incorporated, a biotechnology company, engages in developing and commercializing therapies for treating cystic fibrosis. The company markets SYMDEKO/SYMKEVI, ORKAMBI, and KALYDECO to treat patients with cystic fibrosis who have specific mutations in their cystic fibrosis transmembrane conductance regulator gene; and TRIKAFTA for the treatment of patients with CF 6 years of age or older who have at least one F508del mutation. Its pipeline includes VX-864 for the treatment of AAT deficiency, which is in Phase 2 clinical trial; VX-147 for the treatment of APOL1-mediated focal segmental glomerulosclerosis, or FSGS, and other serious kidney diseases which is in Phase 2 clinical trial; VX- 880, treatment for Type 1 Diabetes which is in Phase 1/2 clinical trial; VX-548, a NaV1.8 inhibitor for treatments of acute, neuropathic, musculoskeletal pain which is in Phase 2 clinical trial; and CTX001 for the treatment severe SCD and TDT which is in Phase 3 clinical trial. The company sells its products primarily to specialty pharmacy and specialty distributors in the United States, as well as specialty distributors and retail chains, and hospitals and clinics internationally. It has collaborations with Affinia Therapeutics, Inc.; Arbor Biotechnologies, Inc.; CRISPR Therapeutics AG.; Kymera Therapeutics, Inc.; Mammoth Biosciences, Inc.; Moderna, Inc.; Obsidian Therapeutics, Inc.; and Skyhawk Therapeutics, Inc.; as well as Ribometrix, Inc.; Genomics plc; Merck KGaA; Darmstadt, Germany, and X-Chem, Inc. Vertex Pharmaceuticals Incorporated was founded in 1989 and is headquartered in Boston, Massachusetts.', 1991, 'Boston, MA, US', 6100, NULL, true, 'VRTX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(16, 'United Therapeutics Corporation', 'united-therapeutics-corporation', 'https://www.unither.com', 'https://images.financialmodelingprep.com/symbol/UTHR.png', 'United Therapeutics Corporation, a biotechnology company, engages in the development and commercialization of products to address the unmet medical needs of patients with chronic and life-threatening diseases in the United States and internationally. Its commercial therapies include Remodulin to treat patients with pulmonary arterial hypertension (PAH) to diminish symptoms associated with exercise; Tyvaso, an inhaled formulation of prostacyclin analogue treprostinil to enhance the exercise ability in PAH patients and pulmonary hypertension associated with interstitial lung disease (PH-ILD); Orenitram, a tablet dosage form of treprostinil to enhance the exercise capacity in PAH patients; Unituxin, a monoclonal antibody for treating high-risk neuroblastoma; and Adcirca, an oral PDE-5 inhibitor to enhance the exercise ability in PAH patients. The company also engages in developing Tyvaso DPI, a dry powder inhalation form of Tyvaso; Remunity Pump, a small, lightweight, durable pump and separate controller; RemoPro and Ralinepag for the treatment of PAH; Aurora-GT, a gene therapy product to rebuild the blood vessels in the lungs; and Tyvaso PERFECT and TETON studies, which are the studies of Tyvaso in patients with World Health Organization (WHO) Group 3 pulmonary hypertension associated with chronic obstructive pulmonary disease (PH-COPD). It has licensing and collaboration agreements with DEKA Research & Development Corp. to develop a semi-disposable system for the subcutaneous delivery of treprostinil; MannKind Corporation to develop and license treprostinil inhalation powder and the Dreamboat device; and Arena Pharmaceuticals, Inc. to develop Ralinepag. The company was incorporated in 1996 and is headquartered in Silver Spring, Maryland.', 1999, 'Silver Spring, MD, US', 1305, NULL, true, 'UTHR', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(22, 'Jazz Pharmaceuticals plc', 'jazz-pharmaceuticals-plc', 'https://www.jazzpharma.com', 'https://images.financialmodelingprep.com/symbol/JAZZ.png', 'Jazz Pharmaceuticals plc, a biopharmaceutical company, identifies, develops, and commercializes pharmaceutical products for various unmet medical needs in the United States, Europe, and internationally. The company has a portfolio of products and product candidates with a focus in the areas of neuroscience, including sleep medicine and movement disorders; and in oncology, including hematologic and solid tumors. Its lead marketed products include Xyrem, an oral solution for the treatment of cataplexy and excessive daytime sleepiness (EDS) in narcolepsy patients seven years of age and older; Sunosi for the treatment of EDS in patients with narcolepsy and obstructive sleep apnea; Erwinaze to treat acute lymphoblastic leukemia; Defitelio for the treatment of adult and pediatric patients with hepatic veno-occlusive disease; Vyxeos liposome for injection, a product for the treatment of adults with newly-diagnosed therapy-related acute myeloid leukemia; and Zepzelca for the treatment of adult patients with metastatic small cell lung cancer. The company also offers Xywav, an oxybate product candidate, to treat EDS and cataplexy with narcolepsy and idiopathic hypersomnia; JZP-324, a low sodium oxybate formulation with the potential to provide a clinically meaningful option for narcolepsy patients; JZP385, a T-type calcium channel modulator, for the treatment of essential tremor; JZP458, a recombinant Erwinia asparaginase, for use as a component of a multi-agent chemotherapeutic regimen in the treatment of pediatric and adult patients; and JZP150 for treatment of post-traumatic stress disorder. The company has licensing and collaboration agreements with ImmunoGen, Inc.; Codiak BioSciences, Inc.; Pfenex, Inc.; XL-protein GmbH; and Redx Pharma plc. Jazz Pharmaceuticals plc was incorporated in 2003 and is headquartered in Dublin, Ireland.', 2007, 'Dublin, IE', 2800, NULL, true, 'JAZZ', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(17, 'Moderna, Inc.', 'moderna-inc', 'https://www.modernatx.com', 'https://images.financialmodelingprep.com/symbol/MRNA.png', 'Moderna, Inc., a biotechnology company, discovers, develops, and commercializes messenger RNA therapeutics and vaccines for the treatment of infectious diseases, immuno-oncology, rare diseases, cardiovascular diseases, and auto-immune diseases in the United States, Europe, and internationally. Its respiratory vaccines include COVID-19, flu, respiratory syncytial virus, Endemic HCoV, and hMPV+PIV3 vaccines; latent vaccines comprise cytomegalovirus, epstein-barr virus, human immunodeficiency virus, herpes simplex virus, and varicella-zoster virus vaccines; and public health vaccines consists of Zika and Nipah vaccines. The company also offers systemic secreted and cell surface therapeutics; cancer vaccines, such as personalized cancer, KRAS, and checkpoint vaccines; intratumoral immuno-oncology products; localized regenerative, systemic intracellular, and inhaled pulmonary therapeutics. It has strategic alliances with AstraZeneca PLC; Merck & Co., Inc.; Vertex Pharmaceuticals Incorporated; Vertex Pharmaceuticals (Europe) Limited; Carisma Therapeutics, Inc.; Metagenomi, Inc.; the Defense Advanced Research Projects Agency; Biomedical Advanced Research and Development Authority; Institute for Life Changing Medicines; and The Bill & Melinda Gates Foundation, as well as a collaboration and license agreement with Chiesi Farmaceutici S.P.A. The company was formerly known as Moderna Therapeutics, Inc. and changed its name to Moderna, Inc. in August 2018. Moderna, Inc. was founded in 2010 and is headquartered in Cambridge, Massachusetts.', 2018, 'Cambridge, MA, US', 5800, NULL, true, 'MRNA', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(18, 'Incyte Corporation', 'incyte-corporation', 'https://www.incyte.com', 'https://images.financialmodelingprep.com/symbol/INCY.png', 'Incyte Corporation, a biopharmaceutical company, focuses on the discovery, development, and commercialization of proprietary therapeutics in the United States and internationally. The company offers JAKAFI, a drug for the treatment of myelofibrosis and polycythemia vera; PEMAZYRE, a fibroblast growth factor receptor kinase inhibitor that act as oncogenic drivers in various liquid and solid tumor types; and ICLUSIG, a kinase inhibitor to treat chronic myeloid leukemia and philadelphia-chromosome positive acute lymphoblastic leukemia. Its clinical stage products include ruxolitinib, a steroid-refractory chronic graft-versus-host-diseases (GVHD); itacitinib, which is in Phase II/III clinical trial to treat naive chronic GVHD; and pemigatinib for treating bladder cancer, cholangiocarcinoma, myeloproliferative syndrome, and tumor agnostic. In addition, the company engages in developing Parsaclisib, which is in Phase II clinical trial for follicular lymphoma, marginal zone lymphoma, and mantel cell lymphoma. Additionally, it develops Retifanlimab that is in Phase II clinical trials for MSI-high endometrial cancer, merkel cell carcinoma, and anal cancer, as well as in Phase II clinical trials for patients with non-small cell lung cancer. It has collaboration agreements with Novartis International Pharmaceutical Ltd.; Eli Lilly and Company; Agenus Inc.; Calithera Biosciences, Inc; MacroGenics, Inc.; Merus N.V.; Syros Pharmaceuticals, Inc.; Innovent Biologics, Inc.; Zai Lab Limited; Cellenkos, Inc.; and Nimble Therapeutics, as well as clinical collaborations with MorphoSys AG and Xencor, Inc. to investigate the combination of tafasitamab, plamotamab, and lenalidomide in patients with relapsed or refractory diffuse large B-cell lymphoma, and relapsed or refractory follicular lymphoma. The company was incorporated in 1991 and is headquartered in Wilmington, Delaware.', 1993, 'Wilmington, DE, US', 2617, NULL, true, 'INCY', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(19, 'Sarepta Therapeutics, Inc.', 'sarepta-therapeutics-inc', 'https://www.sarepta.com', 'https://images.financialmodelingprep.com/symbol/SRPT.png', 'Sarepta Therapeutics, Inc., a commercial-stage biopharmaceutical company, focuses on the discovery and development of RNA-targeted therapeutics, gene therapies, and other genetic therapeutic modalities for the treatment of rare diseases. It offers EXONDYS 51 injection to treat duchenne muscular dystrophy (duchenne) in patients with confirmed mutation of the dystrophin gene that is amenable to exon 51 skipping; and VYONDYS 53 for the treatment of duchenne in patients with confirmed mutation of the dystrophin gene that is amenable to exon 53 skipping. The company is also developing AMONDYS 45, a product candidate that uses phosphorodiamidate morpholino oligomer chemistry and exon-skipping technology to skip exon 45 of the dystrophin gene; SRP-5051, a peptide conjugated PMO that binds exon 51 of dystrophin pre-mRNA; SRP-9001, a DMD micro-dystrophin gene therapy program; and SRP-9003, a limb-girdle muscular dystrophies gene therapy program. It has collaboration agreements with F. Hoffman-La Roche Ltd; Nationwide Children''s Hospital; Lysogene; Duke University; Genethon; and StrideBio. The company was incorporated in 1980 and is headquartered in Cambridge, Massachusetts.', 1997, 'Cambridge, MA, US', 1372, NULL, true, 'SRPT', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(20, 'Vaxcyte, Inc.', 'vaxcyte-inc', 'https://vaxcyte.com', 'https://images.financialmodelingprep.com/symbol/PCVX.png', 'Vaxcyte, Inc., a clinical-stage biotechnology vaccine company, develops novel protein vaccines to prevent or treat bacterial infectious diseases. Its lead vaccine candidate is VAX-24, a 24-valent investigational pneumococcal conjugate vaccine that is in Phase 1/2 clinical trials to treat invasive pneumococcal disease and pneumonia. The company also develops VAX-XP to protect against emerging strains and address antibiotic resistance; VAX-A1, a conjugate vaccine candidate designed to treat Group A Strep; and VAX-PG, a novel protein vaccine candidate targeting keystone pathogen responsible for periodontitis. The company was formerly known as SutroVax, Inc. and changed its name to Vaxcyte, Inc. in May 2020. Vaxcyte, Inc. was incorporated in 2013 and is headquartered in San Carlos, California.', 2020, 'San Carlos, CA, US', 414, NULL, true, 'PCVX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(21, 'Bio-Techne Corporation', 'bio-techne-corporation', 'https://www.bio-techne.com', 'https://images.financialmodelingprep.com/symbol/TECH.png', 'Bio-Techne Corporation, together with its subsidiaries, develops, manufactures, and sells life science reagents, instruments, and services for the research and clinical diagnostic markets worldwide. The company operates through two segments, Protein Sciences, and Diagnostics and Genomics. The Protein Sciences segment develops and manufactures biological reagents used in various aspects of life science research, diagnostics, and cell and gene therapy, such as cytokines and growth factors, antibodies, small molecules, tissue culture sera, and cell selection technologies. This segment also offers proteomic analytical tools for automated western blot and multiplexed ELISA workflow consists of manual and automated protein analysis instruments and immunoassays for use in quantifying proteins in various biological fluids. The Diagnostics and Genomics segment develops and manufactures diagnostic products, including controls, calibrators, and diagnostic assays for regulated diagnostics market, exosome-based molecular diagnostic assays, advanced tissue-based in-situ hybridization assays for spatial genomic and tissue biopsy analysis, and genetic and oncology kits for research and clinical applications; and sells products for genetic carrier screening, oncology diagnostics, molecular controls, and research, as well as instruments and process control products for hematology, blood chemistry and gases, and coagulation controls and reagents used in various diagnostic applications. It offers its products under R&D Systems, Tocris Biosciences, Novus Biologicals, ProteinSimple, Advanced Cell Diagnostics, Exosome Diagnostics, and Asuragen brands. The company was formerly known as Techne Corporation and changed its name to Bio-Techne Corporation in November 2014. Bio-Techne Corporation was founded in 1976 and is headquartered in Minneapolis, Minnesota.', 1989, 'Minneapolis, MN, US', 3100, NULL, true, 'TECH', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(23, 'Ascendis Pharma A/S', 'ascendis-pharma-as', 'https://ascendispharma.com', 'https://images.financialmodelingprep.com/symbol/ASND.png', 'Ascendis Pharma A/S, a biopharmaceutical company, focuses on developing therapeutics for unmet medical needs. The company offers SKYTROFA for treating patients with growth hormone deficiency (GHD). It also develops TransCon Growth Hormone (hGH) for pediatric GHD in Japan; TransCon hGH for adults with GHD; TransCon parathyroid hormone for adult hypoparathyroidism; and TransCon CNP for pediatric achondroplasia. In addition, the company develops TransCon toll like receptors 7/8 agonist for intratumoral delivery; and TransCon IL-2 ß/g for systemic delivery. The company was incorporated in 2006 and is headquartered in Hellerup, Denmark.', 2015, 'Hellerup, DK', 1017, NULL, true, 'ASND', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(24, 'BioMarin Pharmaceutical Inc.', 'biomarin-pharmaceutical-inc', 'https://www.biomarin.com', 'https://images.financialmodelingprep.com/symbol/BMRN.png', 'BioMarin Pharmaceutical Inc. develops and commercializes therapies for people with serious and life-threatening rare diseases and medical conditions. Its commercial products include Vimizim, an enzyme replacement therapy for the treatment of mucopolysaccharidosis (MPS) IV type A, a lysosomal storage disorder; Naglazyme, a recombinant form of N-acetylgalactosamine 4-sulfatase for patients with MPS VI; and Kuvan, a proprietary synthetic oral form of 6R-BH4 that is used to treat patients with phenylketonuria (PKU), an inherited metabolic disease. The company''s commercial products also comprise Palynziq, a PEGylated recombinant phenylalanine ammonia lyase enzyme, which is delivered through subcutaneous injection to reduce blood Phe concentrations; Brineura, a recombinant human tripeptidyl peptidase 1 for the treatment of patients with ceroid lipofuscinosis type 2, a form of Batten disease; Voxzogo, a once daily injection analog of c-type natriuretic peptide for the treatment of achondroplasia; and Aldurazyme, a purified protein designed to be identical to a naturally occurring form of the human enzyme alpha-L-iduronidase. In addition, it develops valoctocogene roxaparvovec, an adeno associated virus vector, which is in Phase III clinical trial for the treatment of patients with severe hemophilia A; BMN 307, an AAV5 mediated gene therapy, which is in Phase 1/2 clinical trial to normalize blood Phe concentration levels in patients with PKU; and BMN 255 that is in Phase 1/2 clinical trial for treating primary hyperoxaluria. The company serves specialty pharmacies, hospitals, and non-U.S. government agencies, as well as distributors and pharmaceutical wholesalers in the United States, Europe, Latin America, and internationally. BioMarin Pharmaceutical Inc. has license and collaboration agreements with Sarepta Therapeutics, Ares Trading S.A., Catalyst Pharmaceutical Partners, Inc., and Asubio Pharma Co., Ltd. The company was incorporated in 1996 and is headquartered in San Rafael, California.', 1999, 'San Rafael, CA, US', 3040, NULL, true, 'BMRN', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(25, 'Exelixis, Inc.', 'exelixis-inc', 'https://www.exelixis.com', 'https://images.financialmodelingprep.com/symbol/EXEL.png', 'Exelixis, Inc., an oncology-focused biotechnology company, focuses on the discovery, development, and commercialization of new medicines to treat cancers in the United States. The company''s products include CABOMETYX tablets for the treatment of patients with advanced renal cell carcinoma who received prior anti-angiogenic therapy; and COMETRIQ capsules for the treatment of patients with progressive and metastatic medullary thyroid cancer. Its CABOMETYX and COMETRIQ are derived from cabozantinib, an inhibitor of multiple tyrosine kinases, including MET, AXL, RET, and VEGF receptors. The company also offers COTELLIC, an inhibitor of MEK as a combination regimen to treat advanced melanoma; and MINNEBRO, an oral non-steroidal selective blocker of the mineralocorticoid receptor for the treatment of hypertension in Japan. In addition, it is developing XL092, an oral tyrosine kinase inhibitor that targets VEGF receptors, MET, AXL, MER, and other kinases implicated in growth and spread of cancer; XB002, an antibody-drug conjugate composed of human mAb against tissue factor (TF) for the treatment of advanced solid tumors; XL102, an orally bioavailable cyclin-dependent kinase 7 (CDK7) inhibitor for the treatment of advanced or metastatic solid tumors; and XB002 for the treatment of non-hodgkin''s lymphoma. Exelixis, Inc. has research collaborations and license agreements with Ipsen Pharma SAS; Takeda Pharmaceutical Company Ltd.; F. Hoffmann-La Roche Ltd.; Redwood Bioscience, Inc.; R.P. Scherer Technologies, LLC; Catalent Pharma Solutions, Inc.; NBE Therapeutics AG; Aurigene Discovery Technologies Limited; Iconic Therapeutics, Inc.; Invenra, Inc.; StemSynergy Therapeutics, Inc.; Genentech, Inc.; Bristol-Myers Squibb Company; and Daiichi Sankyo Company, Limited. The company was formerly known as Exelixis Pharmaceuticals, Inc. and changed its name to Exelixis, Inc. in February 2000. Exelixis, Inc. was incorporated in 1994 and is headquartered in Alameda, California.', 2000, 'Alameda, CA, US', 1147, NULL, true, 'EXEL', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(26, 'Halozyme Therapeutics, Inc.', 'halozyme-therapeutics-inc', 'https://www.halozyme.com', 'https://images.financialmodelingprep.com/symbol/HALO.png', 'Halozyme Therapeutics, Inc. operates as a biopharma technology platform company in the United States, Switzerland, Ireland, Belgium, Japan, and internationally. The company''s products are based on the ENHANZE drug delivery technology, a patented recombinant human hyaluronidase enzyme (rHuPH20) that enables the subcutaneous delivery of injectable biologics, such as monoclonal antibodies and other therapeutic molecules, as well as small molecules and fluids. Its flagship product is Hylenex recombinant, a formulation of rHuPH20 to facilitate subcutaneous fluid administration for achieving hydration to enhance the dispersion and absorption of other injected drugs in subcutaneous urography and to improve resorption of radiopaque agents. The company also develops Perjeta; RITUXAN HYCELA and MabThera SC for the treatment of non-Hodgkin lymphoma and chronic lymphocytic leukemia (CLL); RITUXAN SC for patients with CLL; and HYQVIA for the treatment of immunodeficiency disorders. In addition, it is developing Tecentriq for non-small cell lung cancer; OCREVUS for multiple sclerosis; DARZALEX for the treatment of patients with amyloidosis, smoldering myeloma, and multiple myeloma; nivolumab for the treatment of solid tumors; ARGX-113, a human neonatal Fc receptor; ARGX-117 to treat autoimmune diseases; and BMS-986179, an anti-CD-73 antibody. The company has collaborations with F. Hoffmann-La Roche, Ltd.; Hoffmann-La Roche, Inc.; Baxalta US Inc.; Baxalta GmbH; Pfizer Inc.; Janssen Biotech, Inc.; AbbVie, Inc.; Eli Lilly and Company; Bristol-Myers Squibb Company; Alexion Pharma Holding; ARGENX BVBA; Horizon Therapeutics plc; National Institute of Allergy and Infectious Diseases; Centre for the AIDS Programme of Research in South Africa; and ViiV Healthcare Limited for small and large molecule targets for the treatment and prevention of HIV. Halozyme Therapeutics, Inc. was founded in 1998 and is based in San Diego, California.', 2004, 'San Diego, CA, US', 350, NULL, true, 'HALO', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(27, 'BridgeBio Pharma, Inc.', 'bridgebio-pharma-inc', 'https://www.bridgebio.com', 'https://images.financialmodelingprep.com/symbol/BBIO.png', 'BridgeBio Pharma, Inc. engages in the discovery, development, and delivery of various medicines for genetic diseases. The company has a pipeline of 30 development programs that include product candidates ranging from early discovery to late-stage development. Its products in development programs include AG10 and BBP-265, a small molecule stabilizer of transthyretin, or TTR that is in Phase 3 clinical trial for the treatment of TTR amyloidosis-cardiomyopathy, or ATTR-CM; BBP-831, a small molecule selective FGFR1-3 inhibitor, which is Phase 2 clinical trial to treat achondroplasia in pediatric patients; and BBP-631, an AAV5 gene transfer product candidate that is in Phase 2 clinical trial for the treatment of congenital adrenal hyperplasia, or CAH, driven by 21-hydroxylase deficiency, or 21OHD. The company also develops Encaleret, a small molecule antagonist of the calcium sensing receptor, or CaSR, which is in phase 2 proof-of-concept clinical trial for Autosomal Dominant Hypocalcemia Type 1, or ADH1; and BBP-711 for the treatment of hyperoxaluria, as well as patients suffering from recurrent kidney stones. In addition, it engages in developing products for Mendelian, oncology, and gene therapy diseases. BridgeBio Pharma, Inc. has license and collaboration agreements with the Leland Stanford Junior University; and The Regents of the University of California; Leidos Biomedical Research, Inc. The company was founded in 2015 and is headquartered in Palo Alto, California.', 2019, 'Palo Alto, CA, US', 725, NULL, true, 'BBIO', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(34, 'Revolution Medicines, Inc.', 'revolution-medicines-inc', 'https://www.revmed.com', 'https://images.financialmodelingprep.com/symbol/RVMD.png', 'Revolution Medicines, Inc., a clinical-stage precision oncology company, focuses on developing therapies to inhibit frontier targets in RAS-addicted cancers. The company is developing RMC-4630, an inhibitor of SHP2, which is in Phase 1/2 clinical trial for the treatment of solid tumors, such as gynecologic and colorectal cancer tumors. It also develops RMC-5845, a selective inhibitor of SOS1, a protein that converts RAS (OFF) to RAS (ON) in cells; and RMC-5552, a hyperactivated selective inhibitor of mTORC1 signaling in tumors. In addition, the company is developing RMC-6291, a mutant-selective inhibitor of KRASG12C(ON) and NRASG12C(ON); and RMC-6236, a RAS-selective inhibitor of multiple RAS(ON) variants. Further, it develops RAS(ON) Inhibitors targeting KRASG13C(ON) and KRASG12D(ON). The company has a collaboration agreement with Sanofi for the research and development of SHP2 inhibitors, including RMC-4630. Revolution Medicines, Inc. was incorporated in 2014 and is headquartered in Redwood City, California.', 2020, 'Redwood City, CA, US', 534, NULL, true, 'RVMD', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(28, 'Axsome Therapeutics, Inc.', 'axsome-therapeutics-inc', 'https://www.axsome.com', 'https://images.financialmodelingprep.com/symbol/AXSM.png', 'Axsome Therapeutics, Inc., a biopharmaceutical company, engages in the development of novel therapies for central nervous system (CNS) disorders in the United States. The company''s product pipeline includes AXS-05, a therapeutic for the treatment of major depressive disorder and resistant depression disorders; and that is in the Phase III clinical trial to treat Alzheimer''s disease agitation, as well as that has completed phase II clinical trial for the treatment of smoking cessation. It is also developing AXS-07, a novel, oral, rapidly absorbed, multi-mechanistic, and investigational medicine that has completed two Phase III trials for the acute treatment of migraine; AXS-12, a selective and potent norepinephrine reuptake inhibitor, which is in Phase III trial to treat narcolepsy; and AXS-14, a novel, oral, and investigational medicine that is in Phase III trial for the treatment of fibromyalgia. Axsome Therapeutics, Inc. has a research collaboration agreement with Duke University for evaluating AXS-05 in smoking cessation. The company was incorporated in 2012 and is based in New York, New York.', 2015, 'New York, NY, US', 683, NULL, true, 'AXSM', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(29, 'Corcept Therapeutics Incorporated', 'corcept-therapeutics-incorporated', 'https://www.corcept.com', 'https://images.financialmodelingprep.com/symbol/CORT.png', 'Corcept Therapeutics Incorporated discovers, develops, and commercializes drugs for the treatment of severe metabolic, oncologic, and neuropsychiatric disorders in the United States. The company offers Korlym (mifepristone) tablets as a once-daily oral medication for the treatment of hyperglycemia secondary to hypercortisolism in adult patients with endogenous Cushing''s syndrome, who have type 2 diabetes mellitus or glucose intolerance, and have failed surgery or are not candidates for surgery. It is developing relacorilant to treat patients with Cushing''s syndrome; and nab-paclitaxel in combination with relacorilant, which has completed Phase II clinical trial to treat patients with advanced ovarian tumors, as well as for the treatment of cortisol excess. The company is also developing selective cortisol modulator to treat patients with metastatic castration-resistant prostate cancer; selective cortisol modulator for the treatment of antipsychotic-induced weight gain and other disorders; and FKBP5 gene expression assays. Corcept Therapeutics Incorporated was incorporated in 1998 and is headquartered in Menlo Park, California.', 2004, 'Menlo Park, CA, US', 500, NULL, true, 'CORT', 'NASDAQ Capital Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(30, 'Blueprint Medicines Corporation', 'blueprint-medicines-corporation', 'https://www.blueprintmedicines.com', 'https://images.financialmodelingprep.com/symbol/BPMC.png', 'Blueprint Medicines Corporation, a precision therapy company, develops medicines for genomically defined cancers and blood disorders in the United States and internationally. The company is developing AYVAKIT for the treatment of systemic mastocytosis (SM) and gastrointestinal stromal tumors; BLU-263, an orally available, potent, and KIT inhibitor for the treatment of non-advanced SM and other mast cell disorders; and Fisogatinib, an orally available and potent inhibitor for the treatment of hepatocellular carcinoma. It is also developing GAVRETO for the treatment of RET fusion-positive non-small cell lung cancer, altered solid tumors, medullary thyroid carcinoma, and other solid tumors; BLU-701 and BLU-945 for the treatment of epidermal growth factor receptor driven non-small-cell lung carcinoma (NSCLC); and BLU-451 to treat NSCLC in patients with epidermal growth factor receptor gene (EGFR) exon 20 insertion mutations. In addition, the company is developing BLU-782, for the treatment of fibrodysplasia ossificans progressive; BLU- 222 to treat patients with cyclin E aberrant cancers; and BLU-852 for the treatment of advanced cancers. It has collaboration and license agreements with Clementia Pharmaceuticals, Inc.; Proteovant Therapeutics; CStone Pharmaceuticals; Genentech, Inc.; F. Hoffmann-La Roche Ltd and Hoffmann-La Roche Inc.; and Zai Lab (Shanghai) Co., Ltd. The company was formerly known as Hoyle Pharmaceuticals, Inc. and changed its name to Blueprint Medicines Corporation in June 2011. Blueprint Medicines Corporation was incorporated in 2008 and is headquartered in Cambridge, Massachusetts.', 2015, 'Cambridge, MA, US', 649, NULL, true, 'BPMC', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(31, 'Legend Biotech Corporation', 'legend-biotech-corporation', 'https://www.legendbiotech.com', 'https://images.financialmodelingprep.com/symbol/LEGN.png', 'Legend Biotech Corporation, a clinical-stage biopharmaceutical company, through its subsidiaries, engages in the discovery and development of novel cell therapies for oncology and other indications in the United States, China, and internationally. Its lead product candidate, LCAR- B38M, is a chimeric antigen receptor for the treatment of multiple myeloma (MM), as well as a comparison of the treatment with standard triplet therapy in revlimid-refractory multiple myeloma. The company also has a portfolio of earlier-stage autologous product candidates, which are in Phase I clinical trials for the treatment of gastric cancer and T cell lymphoma. In addition, it is developing CAR-T product candidates targeting CD20/CD22/CD19 for the treatment of non-hodgkins lymphoma, diffuse large B-cell lymphoma, and acute lymphoblastic leukemia. Further, the company has product candidates in early preclinical and clinical development for the treatment of solid tumors as well as infectious diseases. It has collaboration and license agreement with Janssen Biotech, Inc. for the development and commercialization of ciltacabtagene autoleucel. Legend Biotech Corporation was founded in 2014 and is based in Somerset, New Jersey. Legend Biotech Corporation is a subsidiary of Genscript Biotech Corporation.', 2020, 'Somerset, NJ, US', 2500, NULL, true, 'LEGN', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(32, 'Madrigal Pharmaceuticals, Inc.', 'madrigal-pharmaceuticals-inc', 'https://www.madrigalpharma.com', 'https://images.financialmodelingprep.com/symbol/MDGL.png', 'Madrigal Pharmaceuticals, Inc., a clinical-stage biopharmaceutical company, focuses on the development and commercialization of therapeutic candidates for the treatment of cardiovascular, metabolic, and liver diseases. Its lead product candidate is resmetirom, a liver-directed selective thyroid hormone receptor-ß agonist, which is in Phase III clinical trials for the treatment of non-alcoholic steatohepatitis. The company also develops MGL-3745, a backup compound to resmetirom. It has research, development, and commercialization agreement with Hoffmann-La Roche. Madrigal Pharmaceuticals, Inc. is headquartered in West Conshohocken, Pennsylvania.', 2007, 'West Conshohocken, PA, US', 528, NULL, true, 'MDGL', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(33, 'Roivant Sciences Ltd.', 'roivant-sciences-ltd', 'https://roivant.com', 'https://images.financialmodelingprep.com/symbol/ROIV.png', 'Roivant Sciences Ltd., a biopharmaceutical and healthcare technology company that researches and develops medicines. The company develops product candidates for the treatment of various therapeutics, including solid tumors, sickle cell diseases, hypophosphatasia, oncologic malignancies, psoriasis, atopic dermatitis, vitiligo, hyperhidrosis, acne, myasthenia gravis, warm autoimmune hemolytic anemia, thyroid eye diseases, sarcoidosis, and staph aureus bacteremia. The company was founded in 2014 and is based in London, the United Kingdom.', 2020, 'London, GB', 908, NULL, true, 'ROIV', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(35, 'TG Therapeutics, Inc.', 'tg-therapeutics-inc', 'https://www.tgtherapeutics.com', 'https://images.financialmodelingprep.com/symbol/TGTX.png', 'TG Therapeutics, Inc., a commercial stage biopharmaceutical company, focuses on the acquisition, development, and commercialization of novel treatments for B-cell malignancies and autoimmune diseases. Its therapeutic product candidates include Ublituximab, an investigational glycoengineered monoclonal antibody for the treatment of B-cell non-hodgkin lymphoma, chronic lymphocytic leukemia (CLL), and relapsing forms of multiple sclerosis; and Umbralisib, an oral inhibitor of PI3K-delta and CK1-epsilon for the treatment of CLL, marginal zone lymphoma, and follicular lymphoma. The company also develops Cosibelimab, a human monoclonal antibody of IgG1 subtype that binds to programmed death-ligand 1 (PD-L1) and blocks its interactions with PD-1 and B7.1 receptors; TG-1701 is an orally available and covalently-bound Bruton''s tyrosine kinase (BTK) inhibitor that exhibits selectivity to BTK compared to ibrutinib in in vitro kinase screening; and TG-1801, a bispecific CD47 and CD19 antibody. In addition, it has various licensed preclinical programs for BET, interleukin-1 receptor associated kinase-4, and GITR; and collaboration agreements with Checkpoint Therapeutics, Inc., Jiangsu Hengrui Medicine Co., Novimmune SA, Ligand Pharmaceuticals Incorporated, and Jubilant Biosys. The company has strategic alliances with LFB Biotechnologies S.A.S; GTC Biotherapeutics; LFB/GTC LLC; Ildong Pharmaceutical Co. Ltd.; and Rhizen Pharmaceuticals, S A. TG Therapeutics, Inc. was incorporated in 1993 and is headquartered in New York, New York.', 2010, 'New York, NY, US', 338, NULL, true, 'TGTX', 'NASDAQ Capital Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(36, 'Telix Pharmaceuticals Limited', 'telix-pharmaceuticals-limited', 'https://telixpharma.com', 'https://images.financialmodelingprep.com/symbol/TLX.png', 'Telix Pharmaceuticals Limited, a commercial-stage biopharmaceutical company, focuses on the development and commercialization of therapeutic and diagnostic radiopharmaceuticals for cancer and rare diseases in Australia, Belgium, Japan, Switzerland, and the United States. The company offers Illuccix for the treatment of prostate cancer; and TLX66-CDx for the treatment of imaging osteomyelitis. Its products candidates include TLX591, a radio antibody-drug conjugate for the treatment of prostate cancer; TLX250-CDx for the treatment and diagnosis of renal (kidney) cancer; TLX101-CDx for brain (glioma) cancer; TLX66-CDx to treat bone marrow conditioning; TLX300-CDx for the treatment and diagnosis of soft tissue sarcoma; and TLX250 for the treatment of clear cell renal cell carcinoma. The company also develops TLX101 for the treatment of glioblastoma (brain cancer); TLX66 for the treatment of bone marrow conditioning; TLX300 for the treatment of soft tissue sarcoma; and TLX592, a prostate cancer therapy candidate for targeted alpha therapy. Telix Pharmaceuticals Limited was founded in 2015 and is headquartered in North Melbourne, Australia.', 2024, 'North Melbourne, VIC, AU', NULL, NULL, true, 'TLX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(37, 'Pharming Group N.V.', 'pharming-group-nv', 'https://www.pharming.com', 'https://images.financialmodelingprep.com/symbol/PHAR.png', 'Pharming Group N.V., a biopharmaceutical company, develops and commercialize protein replacement therapies and precision medicines for the treatment of rare diseases and unmet medical needs in the United States, Europe, and internationally. The company''s lead product is Ruconest, a recombinant human C1 esterase inhibitor that is used for the treatment of acute hereditary angioedema. It also engages in the development of rhC1INH for the treatment of pre-eclampsia, acute kidney injury, and COVID-19; leniolisib, a phosphoinositide 3-kinase delta (PI3K delta) to treat patients with activated PI3K delta syndrome; and alpha-glucosidase therapy for the treatment of pompe and fabry diseases. The company has a development collaboration and license agreement with Novartis; and a strategic collaboration agreement with Orchard Therapeutics plc for research, development, manufacturing, and commercialization of OTL-105, an investigational ex-vivo autologous hematopoietic stem cell gene therapy for the treatment of hereditary angioedema. Pharming Group N.V. is headquartered in Leiden, the Netherlands.', 2020, 'Leiden, NL', 382, NULL, true, 'PHAR', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(38, 'Cytokinetics, Incorporated', 'cytokinetics-incorporated', 'https://www.cytokinetics.com', 'https://images.financialmodelingprep.com/symbol/CYTK.png', 'Cytokinetics, Incorporated, a late-stage biopharmaceutical company, focuses on discovering, developing, and commercializing muscle activators and inhibitors as potential treatments for debilitating diseases. The company develops small molecule drug candidates primarily engineered to impact muscle function and contractility. Its drug candidates include omecamtiv mecarbil, a novel cardiac myosin activator that is in Phase III clinical trial in patients with heart failure; and reldesemtiv, a skeletal muscle troponin activator, which is in Phase III clinical trial to treat amyotrophic lateral sclerosis and spinal muscular atrophy. The company also develops CK-136, a novel cardiac troponin activator that is in Phase I clinical trial; aficamten, a novel cardiac myosin inhibitor, which is in Phase III clinical trial for the treatment of patients with symptomatic obstructive hypertrophic cardiomyopathy; and CK-3772271, a small molecule cardiac myosin inhibitor that is in Phase I clinical trial. Cytokinetics, Incorporated has a strategic alliance with Astellas Pharma Inc. The company was incorporated in 1997 and is headquartered in South San Francisco, California.', 2004, 'South San Francisco, CA, US', 498, NULL, true, 'CYTK', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(39, 'ADMA Biologics, Inc.', 'adma-biologics-inc', 'https://www.admabiologics.com', 'https://images.financialmodelingprep.com/symbol/ADMA.png', 'ADMA Biologics, Inc., a biopharmaceutical company, engages in developing, manufacturing, and marketing specialty plasma-derived biologics for the treatment of immune deficiencies and infectious diseases in the United States and internationally. It offers BIVIGAM, an intravenous immune globulin (IVIG) product indicated for the treatment of primary humoral immunodeficiency (PI); ASCENIV, an IVIG product for the treatment of PI; and Nabi-HB for the treatment of acute exposure to blood containing Hepatitis B surface antigen and other listed exposures to Hepatitis B. The company also develops a pipeline of plasma-derived therapeutics, including products related to the methods of treatment and prevention of S. pneumonia infection for an immunoglobulin. In addition, it operates source plasma collection facilities. The company sells its products through independent distributors, sales agents, specialty pharmacies, and other alternate site providers. ADMA Biologics, Inc. was incorporated in 2004 and is headquartered in Ramsey, New Jersey.', 2013, 'Ramsey, NJ, US', 624, NULL, true, 'ADMA', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(40, 'Alkermes plc', 'alkermes-plc', 'https://www.alkermes.com', 'https://images.financialmodelingprep.com/symbol/ALKS.png', 'Alkermes plc, a biopharmaceutical company, researches, develops, and commercializes pharmaceutical products to address unmet medical needs of patients in various therapeutic areas in the United States, Ireland, and internationally. Its marketed products include ARISTADA, an intramuscular injectable suspension for the treatment of schizophrenia; VIVITROL for the treatment of alcohol and prevention of opioid dependence; RISPERDAL CONSTA for the treatment of schizophrenia and bipolar I disorder; INVEGA SUSTENNA for the treatment of schizophrenia and schizoaffective disorder; XEPLION, INVEGA TRINZA, and TREVICTA to treat schizophrenia and schizoaffective; and VUMERITY for the treatment of relapsing forms of multiple sclerosis in adults, including clinically isolated syndrome, relapsing-remitting and active secondary progressive diseases. The company is also developing LYBALVI, an oral atypical antipsychotic drug candidate for the treatment of adults with schizophrenia and bipolar I disorder; and nemvaleukin alfa, an engineered fusion protein to expand tumor-killing immune cells and to avoid the activation of immunosuppressive cells. It has collaboration agreements primarily with Janssen Pharmaceutica N.V., Janssen Pharmaceutica Inc, and Janssen Pharmaceutica International. Alkermes plc was founded in 1987 and is headquartered in Dublin, Ireland.', 1991, 'Dublin, IE', 1800, NULL, true, 'ALKS', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(41, 'Ionis Pharmaceuticals, Inc.', 'ionis-pharmaceuticals-inc', 'https://www.ionispharma.com', 'https://images.financialmodelingprep.com/symbol/IONS.png', 'Ionis Pharmaceuticals, Inc. discovers and develops RNA-targeted therapeutics in the United States. The company offers SPINRAZA for spinal muscular atrophy (SMA) in pediatric and adult patients; TEGSEDI, an injection for the treatment of polyneuropathy of hereditary transthyretin-mediated amyloidosis in adults; and WAYLIVRA, a treatment for familial chylomicronemia syndrome and familial partial lipodystrophy. It also develops medicines for various indications that are in phase 3 study, including Eplontersen as a monthly self-administered subcutaneous injection to treat all types of TTR amyloidosis; Olezarsen for patients with severe hypertriglyceridemia (SHTG); Donidalorsen for patients with hereditary angioedema; ION363 for patients with amyotrophic lateral sclerosis; Pelacarsen for patients with established cardiovascular disease and elevated lipoprotein(a); and Tofersen to inhibit the production of superoxide dismutase 1. In addition, the company develops medicines for metabolic diseases, infectious diseases, renal diseases, ophthalmic diseases, and cancer. It has a strategic collaboration with Biogen Inc.; and collaboration and license agreement with AstraZeneca, Bayer AG, GlaxoSmithKline plc, Novartis AG, Roche, Janssen Biotech, Inc., and Flamingo Therapeutics, Inc. Ionis Pharmaceuticals, Inc. was founded in 1989 and is based in Carlsbad, California.', 1991, 'Carlsbad, CA, US', 1069, NULL, true, 'IONS', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(42, 'Krystal Biotech, Inc.', 'krystal-biotech-inc', 'https://www.krystalbio.com', 'https://images.financialmodelingprep.com/symbol/KRYS.png', 'Krystal Biotech, Inc., a clinical stage biotechnology company, engages in the field of redosable gene therapy to treat serious rare diseases in the United States. Its lead product candidate is beremagene geperpavec (B-VEC), which is in Phase III clinical study to treat dystrophic epidermolysis bullosa. The company is also involved in developing KB105 that is in Phase I/II clinical study for treating patients with deficient autosomal recessive congenital ichthyosis; KB301, which is in Phase I/II clinical stage for treating wrinkles and other presentations of aged or damaged skin; KB407 that is in preclinical stage for cystic fibrosis; and KB104, which is in preclinical stage for netherton syndrome. Its discovery stage product candidates include KB5xx for treating chronic skin diseases, KB3xx to treat aesthetic skin conditions, and KB3xx product. Krystal Biotech, Inc. was founded in 2015 and is headquartered in Pittsburgh, Pennsylvania.', 2017, 'Pittsburgh, PA, US', 275, NULL, true, 'KRYS', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(43, 'Nuvalent, Inc.', 'nuvalent-inc', 'https://www.nuvalent.com', 'https://images.financialmodelingprep.com/symbol/NUVL.png', 'Nuvalent, Inc., a clinical stage biopharmaceutical company, develops therapies for patients with cancer. Its lead product candidates are NVL-520, a brain-penetrant ROS1-selective inhibitor to inhibit ROS1 fusions that express the normal ROS1 kinase domain without any drug-resistant mutations and remain active in the presence of mutations conferring resistance to approved and investigational ROS1 inhibitors, which is under Phase I development; and NVL-655, a brain-penetrant ALK-selective inhibitor, to address the clinical challenges of emergent treatment resistance, central nervous system-related adverse events, and brain metastases that might limit the use of first-, second-, and third-generation ALK inhibitors that is under Phase I/II clinical trial. The company was incorporated in 2017 and is headquartered in Cambridge, Massachusetts.', 2021, 'Cambridge, MA, US', 142, NULL, true, 'NUVL', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(44, 'PureTech Health plc', 'puretech-health-plc', 'https://www.puretechhealth.com', 'https://images.financialmodelingprep.com/symbol/PRTC.png', 'PureTech Health plc, a clinical-stage biotherapeutics company, discovers, develops, and commercializes medicines for inflammatory, fibrotic and immunological, intractable cancers, lymphatic and gastrointestinal, neurological and neuropsychological, and other diseases in the United States. The company offers KarXT targeting muscarinic acetylcholine receptors to treat schizophrenia and psychosis in Alzheimer''s disease; a regenerative biology platform for androgenetic alopecia, epithelial ageing, and other medical conditions; an immunomodulation platform to treat chronic and acute inflammatory disorders; oral therapies based on defined consortia of bacteria is isolated from the human microbiome; and therapies to treat cognitive dysfunction associated with depression, multiple sclerosis, post COVID and ICU, and cancer related conditions. It also provides hematopoietic stem cell based therapies for patients with blood cancer; a voice-based technology platform to detect voice changes linked to health conditions; and a technology platform for the oral delivery of biologics, vaccines, and other drugs. In addition, the company is developing LYT-100 to treat lymphedema, and other lymphatic flow disorders; LYT-200, a IgG4 monoclonal antibody to target galectin-9; LYT-210 to treat solid tumors; Glyph, a synthetic lymphatic targeting chemistry platform; Orasome technology to enable the oral administration of macromolecule therapeutic payloads; meningeal lymphatics platform to treat Alzheimer''s and Parkinson''s diseases; and Alivio technology platform for inflammation-targeted disease immunomodulation. PureTech Health plc has collaboration and license agreements with Boehringer Ingelheim International GMBH; Eli Lilly and Company; Imbrium Therapeutics L.P.; and Shionogi & Co., Ltd. The company was incorporated in 2015 and is headquartered in Boston, Massachusetts.', 2020, 'Boston, MA, US', 90, NULL, true, 'PRTC', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(50, 'Akero Therapeutics, Inc.', 'akero-therapeutics-inc', 'https://www.akerotx.com', 'https://images.financialmodelingprep.com/symbol/AKRO.png', 'Akero Therapeutics, Inc., a cardio-metabolic nonalcoholic steatohepatitis (NASH) company, engages in the development of medicines designed to restore metabolic balance and improve overall health. The company''s lead product candidate is efruxifermin (EFX), an analog of fibroblast growth factor 21, which protects against cellular stress and regulates metabolism of lipids, carbohydrates, and proteins throughout the body. It also conducts a Phase 2a clinical trial, the BALANCED study, to evaluate EFX in the treatment of biopsy-confirmed NASH patients. The company was formerly known as Pippin Pharmaceuticals, Inc. and changed its name to Akero Therapeutics, Inc. in May 2018. Akero Therapeutics, Inc. was incorporated in 2017 and is headquartered in South San Francisco, California.', 2019, 'South San Francisco, CA, US', 63, NULL, true, 'AKRO', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(45, 'PTC Therapeutics, Inc.', 'ptc-therapeutics-inc', 'https://www.ptcbio.com', 'https://images.financialmodelingprep.com/symbol/PTCT.png', 'PTC Therapeutics, Inc., a biopharmaceutical company, focuses on the discovery, development, and commercialization of medicines to patients with rare disorders. Its portfolio pipeline includes commercial products and product candidates in various stages of development, including clinical, pre-clinical and research and discovery stages, focuses on the development of treatments for multiple therapeutic areas, such as rare diseases. The company offers Translarna and Emflaza for the treatment of Duchenne muscular dystrophy in the European Economic Area and the United States, as well as to treat nonsense mutation Duchenne muscular dystrophy in Brazil and Russia; commercializes Tegsedi and Waylivra for the treatment of rare diseases in Latin America and the Caribbean; and markets Evrysdi for the treatment of spinal muscular atrophy in adults and children two months and older in Brazil. The company''s splicing platform includes PTC518, which is being developed for the treatment of Huntington''s disease. PTC Therapeutics, Inc. has collaborations with F. Hoffman-La Roche Ltd and Hoffman-La Roche Inc., as well as the Spinal Muscular Atrophy Foundation to advance drug discovery and development research in regenerative medicine; and Akcea Therapeutics, Inc. to commercialize Tegsedi and Waylivra for the treatment of rare diseases in Latin America and the Caribbean. PTC Therapeutics, Inc. was incorporated in 1998 and is headquartered in South Plainfield, New Jersey.', 2013, 'South Plainfield, NJ, US', 939, NULL, true, 'PTCT', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(46, 'SpringWorks Therapeutics, Inc.', 'springworks-therapeutics-inc', 'https://www.springworkstx.com', 'https://images.financialmodelingprep.com/symbol/SWTX.png', 'SpringWorks Therapeutics, Inc. acquires, develops, and commercializes medicines for underserved patient populations suffering from rare diseases and cancer. Its lead product candidate is nirogacestat, an oral small molecule gamma secretase inhibitor that is in Phase III clinical trial for the treatment of desmoid tumors. The company is also developing mirdametinib, an oral small molecule MEK inhibitor that is in Phase 2b clinical trials for the treatment of neurofibromatosis type 1-associated plexiform neurofibromas, as well as Phase 1/2a clinical trial for the treatment of NF1-PN; mirdametinib + lifirafenib, a combination therapy that is in Phase 1b/2 clinical trial in patients with advanced or refractory solid tumors; and mirdametinib in monotherapy and combination approaches to treat solid tumors. In addition, it develops BGB-3245, an oral selective small molecule inhibitor of monomeric and dimeric forms of activating BRAF mutations, which is in Phase I clinical trial. The company has collaborations with BeiGene, Ltd., GlaxoSmithKline LLC, and Allogene to develop combination approaches with nirogacestat and mirdametinib; and license agreements with Pfizer Inc. for nirogacestat and mirdametinib. It also has a license agreement with Katholieke Universiteit Leuven and the Flanders Institute for Biotechnology for a portfolio of novel small molecule inhibitors of the TEA Domain; and Dana-Farber Cancer Institute for a portfolio of novel small molecule inhibitors of Epidermal Growth Factor Receptor. In addition, the company has clinical collaboration agreement with Janssen Biotech, Inc., Precision BioSciences, Inc., Seagen Inc., and AbbVie, Inc. SpringWorks Therapeutics, Inc. was founded in 2017 and is headquartered in Stamford, Connecticut.', 2019, 'Stamford, CT, US', 368, NULL, true, 'SWTX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(47, 'Zai Lab Limited', 'zai-lab-limited', 'https://www.zailaboratory.com', 'https://images.financialmodelingprep.com/symbol/ZLAB.png', 'Zai Lab Limited develops and commercializes therapies to treat oncology, autoimmune disorders, infectious diseases, and neuroscience primarily in Mainland China and Hong Kong. The company''s commercial products include Zejula, a once-daily small-molecule poly polymerase 1/2 inhibitor; Optune, a device that delivers tumor treating fields; NUZYRA for acute bacterial skin and skin structure infections, and community acquired bacterial pneumonia; and Qinlock to treat gastrointestinal stromal tumors. It also develops Odronextamab to treat follicular lymphoma, diffuse large B-cell lymphoma, and other B-celllymphomas; Repotrectinib, a tyrosine kinase inhibitor (TKI) to target ROS1 and TRK A/B/C in TKI-naïve- or -pretreated cancer patients; Margetuximab for the treatment of breast and gastroesophageal cancers; Adagrasib for treating KRAS-G12C-mutated NSCLC, colorectal cancer, pancreatic cancer, and other solid tumors; and Bemarituzumab to treat gastric and gastroesophageal junction cancer. In addition, the company develops CLN-081 for the treatment of patients with EGFR exon 20 insertion NSCLC; Elzovantinib, an orally bioavailable multi-targeted kinase inhibitor; Tebotelimab, a tetravalent IgG4 monoclonal antibody; Retifanlimab that inhibits interactions between PD-1 and its ligands; ZL-2309, an orally active, selective, and ATP-competitive cell division cycle 7 (CDC7) kinase inhibitor; ZL-1201, a humanized IgG4 monoclonal antibody; Efgartigimod to reduce disease-causing immunoglobulin G antibodies; ZL-1102, a human nanobody targeting interleukin- 17A; KarXT for the treatment of psychiatric and neurological conditions; ZL-2313, an investigational inhibitor of triple-mutant EGFR harboring; ZL-2314, an investigational inhibitor of double-mutant EGFR harboring; and Sulbactam/durlobactam for the treatment of serious infections caused by Acinetobacter. Zai Lab Limited was incorporated in 2013 and is headquartered in Shanghai, China.', 2017, 'Shanghai, CN', 1869, NULL, true, 'ZLAB', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(48, 'Scholar Rock Holding Corporation', 'scholar-rock-holding-corporation', 'https://scholarrock.com', 'https://images.financialmodelingprep.com/symbol/SRRK.png', 'Scholar Rock Holding Corporation, a biopharmaceutical company, focuses on the discovery and development of medicines for the treatment of serious diseases in which signaling by protein growth factors plays a fundamental role. The company develops Apitegromab, an inhibitor of the activation of latent myostatin that has completed the Phase 3 clinical trials for the treatment of spinal muscular atrophy; and SRK-181, which is in Phase 1 clinical trials for the treatment of cancers that are resistant to checkpoint inhibitor therapies, such as anti-PD-1 or anti-PD-L1 antibody therapies. It is also developing a pipeline of novel product candidates with potential to transform the lives of patients suffering from a range of serious diseases, including neuromuscular disorders, cancer, and fibrosis. The company has a collaboration agreement with Gilead Sciences, Inc. to discover and develop specific inhibitors of transforming growth factor beta activation for the treatment of fibrotic diseases. Scholar Rock Holding Corporation was founded in 2012 and is headquartered in Cambridge, Massachusetts.', 2018, 'Cambridge, MA, US', 128, NULL, true, 'SRRK', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(49, 'Arcellx, Inc.', 'arcellx-inc', 'https://arcellx.com', 'https://images.financialmodelingprep.com/symbol/ACLX.png', 'Arcellx, Inc., a clinical-stage biotechnology company, engages in the development of various immunotherapies for patients with cancer and other incurable diseases. The company''s lead ddCAR product candidate is CART-ddBCMA, which is in phase 1 clinical trial for the treatment of patients with relapsed or refractory (r/r) multiple myeloma (MM). It is also developing ACLX-001, an immunotherapeutic combination composed of ARC-T cells and bi-valent SparX proteins targeting BCMA to treat r/r MM; ACLX-002 and ACLX-003 for treating r/r acute myeloid leukemia (AML) and myelodysplastic syndrome (MDS); and other AML/MDS product candidates, as well as solid tumor programs. The company was formerly known as Encarta Therapeutics, Inc. and changed its name to Arcellx, Inc. in January 2016. Arcellx, Inc. was incorporated in 2014 and is headquartered in Gaithersburg, Maryland.', 2022, 'Gaithersburg, MD, US', 163, NULL, true, 'ACLX', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(51, 'CRISPR Therapeutics AG', 'crispr-therapeutics-ag', 'https://www.crisprtx.com', 'https://images.financialmodelingprep.com/symbol/CRSP.png', 'CRISPR Therapeutics AG, a gene editing company, focuses on developing gene-based medicines for serious diseases using its proprietary Clustered Regularly Interspaced Short Palindromic Repeats (CRISPR)/CRISPR-associated protein 9 (Cas9) platform. Its CRISPR/Cas9 is a gene editing technology that allows for precise directed changes to genomic DNA. The company has a portfolio of therapeutic programs across a range of disease areas, including hemoglobinopathies, oncology, regenerative medicine, and rare diseases. The company''s lead product candidate is CTX001, an ex vivo CRISPR gene-edited therapy for treating patients suffering from transfusion-dependent beta-thalassemia or severe sickle cell disease in which a patient''s hematopoietic stem cells are engineered to produce high levels of fetal hemoglobin in red blood cells. It also develops CTX110, a donor-derived gene-edited allogeneic CAR-T investigational therapy targeting cluster of differentiation 19 positive malignancies; CTX120, a donor-derived gene-edited allogeneic CAR-T investigational therapy targeting B-cell maturation antigen for the treatment of relapsed or refractory multiple myeloma; and CTX130, a donor-derived gene-edited allogeneic CAR-T investigational therapy targeting Cluster of Differentiation 70 to treat various solid tumors and hematologic malignancies. In addition, the company develops VCTX210, a gene-edited immune-evasive stem cell-derived product candidate for the treatment of treatment of type 1 diabetes; and pursues various in vivo gene-editing programs that target the liver, lung, muscle, and central nervous system diseases. It has strategic partnerships with Bayer Healthcare LLC, Vertex Pharmaceuticals Incorporated, ViaCyte, Inc., Nkarta, Inc., and Capsida Biotherapeutics. CRISPR Therapeutics AG was incorporated in 2013 and is headquartered in Zug, Switzerland.', 2016, 'Zug, CH', 393, NULL, true, 'CRSP', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(52, 'Merus N.V.', 'merus-nv', 'https://www.merus.nl', 'https://images.financialmodelingprep.com/symbol/MRUS.png', 'Merus N.V., a clinical-stage immuno-oncology company, engages in the discovery and development of bispecific antibody therapeutics in the Netherlands. Its bispecific antibody candidate pipeline includes Zenocutuzumab (MCLA-128), which is in a phase 2 clinical trials for the treatment of patients with metastatic breast cancer, as well as in Phase 1/2 clinical trials for the treatment of solid tumors that harbor Neuregulin 1. The company is also developing MCLA-158, which is in a phase I clinical trial for the treatment of solid tumors; MCLA-145, which is in phase 1 clinical trials for the treatment of solid tumors; MCLA-129, which is in phase 1/2 clinical trials for the treatment of patients with advanced non-small cell lung cancer and other solid tumors; and ONO-4685 that is Phase 1 clinical trial to treat relapsed/refractory T cell lymphoma. In addition, it has collaboration agreement with Betta Pharmaceuticals Co. Ltd for the research and development of stage bispecific antibody candidates include MCLA-129; and collaboration with Incyte Corporation for the development of MCLA-145. The company was incorporated in 2003 and is headquartered in Utrecht, the Netherlands.', 2016, 'Utrecht, NL', 260, NULL, true, 'MRUS', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(53, 'Protagonist Therapeutics, Inc.', 'protagonist-therapeutics-inc', 'https://www.protagonist-inc.com', 'https://images.financialmodelingprep.com/symbol/PTGX.png', 'Protagonist Therapeutics, Inc., a biopharmaceutical company, discovers and develops peptide-based therapeutic drugs to address hematology and blood disorders, and inflammatory and immunomodulatory diseases. It is developing rusfertide (PTG-300), an injectable hepcidin mimetic that is in Phase II clinical trials for the treatment of patients with polycythemia vera and hereditary hemochromatosis, as well as for the treatment of other blood disorders; PN-943, an oral, alpha-4-beta-7 integrin- specific antagonist peptide that is in Phase II clinical trials for treating inflammatory bowel disease (IBD); and PN-235, an orally delivered interleukin-23 receptor specific antagonist for the treatment of IBD and non-IBD indications. The company has a license and collaboration agreement with Janssen Biotech, Inc. Protagonist Therapeutics, Inc. was incorporated in 2006 and is headquartered in Newark, California.', 2016, 'Newark, CA, US', 126, NULL, true, 'PTGX', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(54, 'Ultragenyx Pharmaceutical Inc.', 'ultragenyx-pharmaceutical-inc', 'https://www.ultragenyx.com', 'https://images.financialmodelingprep.com/symbol/RARE.png', 'Ultragenyx Pharmaceutical Inc., a biopharmaceutical company, focuses on the identification, acquisition, development, and commercialization of novel products for the treatment of rare and ultra-rare genetic diseases in North America, Europe, and internationally. Its biologic products include Crysvita (burosumab), an antibody targeting fibroblast growth factor 23 for the treatment of X-linked hypophosphatemia, as well as tumor-induced osteomalacia; Mepsevii, an enzyme replacement therapy for the treatment of children and adults with Mucopolysaccharidosis VII; Dojolvi for treating long-chain fatty acid oxidation disorders; and Evkeeza (evinacumab) for the treatment of homozygous familial hypercholesterolemia. The company''s products candidatures include DTX401, an adeno-associated virus 8 (AAV8) gene therapy clinical candidate for the treatment of patients with glycogen storage disease type Ia; DTX301, an AAV8 gene therapy for the treatment of patients with ornithine transcarbamylase; UX143, a human monoclonal antibody for the treatment of osteogenesis imperfecta; GTX-102, an antisense oligonucleotide for the treatment of Angelman syndrome; UX701, for the treatment of Wilson disease; and UX053 for the treatment of glycogen storage disease type III. Ultragenyx Pharmaceutical Inc. has collaboration and license agreement with Kyowa Kirin Co., Ltd.; Saint Louis University; Baylor Research Institute; REGENXBIO Inc.; Bayer Healthcare LLC; GeneTx; Mereo; University of Pennsylvania; Arcturus Therapeutics Holdings Inc., Solid Biosciences Inc.; and Daiichi Sankyo Co., Ltd. Ultragenyx Pharmaceutical Inc. was incorporated in 2010 and is headquartered in Novato, California.', 2014, 'Novato, CA, US', 1294, NULL, true, 'RARE', 'NASDAQ Global Select', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00'),
	(55, 'Avidity Biosciences, Inc.', 'avidity-biosciences-inc', 'https://www.aviditybiosciences.com', 'https://images.financialmodelingprep.com/symbol/RNA.png', 'Avidity Biosciences, Inc., a biopharmaceutical company, engages in the development of oligonucleotide-based therapies. It develops antibody oligonucleotide conjugates (AOC) that are designed to treat a range of serious diseases. The company''s lead product candidate AOC 1001 is used for the treatment of myotonic dystrophy type 1, a rare monogenic muscle disease; AOC 1044 for the treatment of Duchenne Muscular Dystrophy; and AOC 1020 designed to treat facioscapulohumeral muscular dystrophy which are in preclinical stage. It also offers Lumizyme therapy for Pompe diseases. Avidity Biosciences, Inc. was incorporated in 2012 and is headquartered in San Diego, California.', 2020, 'San Diego, CA, US', 391, NULL, true, 'RNA', 'NASDAQ Global Market', '2025-03-12 18:14:37.230184+00', '2025-03-12 18:14:37.230184+00');


--
-- Data for Name: buckets; Type: TABLE DATA; Schema: storage; Owner: supabase_storage_admin
--



--
-- Data for Name: objects; Type: TABLE DATA; Schema: storage; Owner: supabase_storage_admin
--



--
-- Data for Name: s3_multipart_uploads; Type: TABLE DATA; Schema: storage; Owner: supabase_storage_admin
--



--
-- Data for Name: s3_multipart_uploads_parts; Type: TABLE DATA; Schema: storage; Owner: supabase_storage_admin
--



--
-- Data for Name: secrets; Type: TABLE DATA; Schema: vault; Owner: supabase_admin
--



--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: auth; Owner: supabase_auth_admin
--

SELECT pg_catalog.setval('"auth"."refresh_tokens_id_seq"', 1, false);


--
-- Name: key_key_id_seq; Type: SEQUENCE SET; Schema: pgsodium; Owner: supabase_admin
--

SELECT pg_catalog.setval('"pgsodium"."key_key_id_seq"', 1, false);


--
-- Name: companies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"public"."companies_id_seq"', 55, true);


--
-- PostgreSQL database dump complete
--

RESET ALL;
